database: postgres
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password:
  application:
    name: Example
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
  sql:
    init:
      mode: always
      schema-locations: classpath*:db/postgres/schema.sql
      data-locations: classpath*:db/postgres/data.sql
server:
  port: 8084

